server:
  port: 8886
  servlet:
    session:
      timeout: 15552000
github:
  client:
    id: 08937290359057a5f107
    secret: 24e2f2dd25827bb64e930564a6352b3d95ecc5a3
  redirect:
    uri: http://localhost:8886/callback

# 云存储
ucloud:
  ufile:
    public-key: TOKEN_2ad53164-f1b5-4a70-ae25-610622a6321f
    private-key: 38db63ca-7581-4d4e-924c-10bfb74c8f89
    bucket-name: work
    region: cn-bj
    suffix: ufileos.com
    expires: 315360000


#spring:
#  datasource:
#    url: jdbc:h2:~/community
#    username: root
#    password: root
#    driver-class-name: org.h2.Driver
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qa?useUnicode=true&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
# 命名_改为驼峰
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
  type-aliases-package: work.ccpw.forum.model
  mapper-locations: classpath:mapper/*.xml

# 日志
logging:
  file:
    max-history: 30
    path: logs/community.log
  level:
    root: info
    work:
      ccpw:
        community:
          mapper: debug


