server:
  port: 8886
github:
  client:
    id: 08937290359057a5f107
    secret: 24e2f2dd25827bb64e930564a6352b3d95ecc5a3
  redirect:
    uri: http://localhost:8886/callback
spring:
  datasource:
    url: jdbc:h2:~/community
    username: root
    password: root
    driver-class-name: org.h2.Driver