server:
  port: 80
github:
  client:
    id: 08937290359057a5f107
    secret: 24e2f2dd25827bb64e930564a6352b3d95ecc5a3
  redirect:
    uri: http://123.57.27.129/callback

# 云存储
ucloud:
  ufile:
    public-key: TOKEN_2ad53164-f1b5-4a70-ae25-610622a6321f
    private-key: 38db63ca-7581-4d4e-924c-10bfb74c8f89
    bucket-name: work
    region: cn-bj
    suffix: ufileos.com
    expires: 315360000


spring:
  datasource:
    url: jdbc:h2:~/community
    username: root
    password: root
    driver-class-name: org.h2.Driver
# 命名_改为驼峰
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
  type-aliases-package: work.ccpw.community.model
  mapper-locations: classpath:mapper/*.xml

# 日志
logging:
  file:
    max-history: 30
    path: logs/community.log
  level:
    root: info
    work:
      ccpw:
        community:
          mapper: debug
  pattern:
    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
    file: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
